### ISSUE TITLE
There is no $log variable specified before call

### ISSUE THREAD

**Issue by trk** [janKir/CacheNesting#1]
You can use `wire()->log->warning()`.

https://github.com/janKir/CacheNesting/blob/9f58d32134e4dd7f306950a69a97ba5a461b7073/CacheNesting.module#L215

https://github.com/janKir/CacheNesting/blob/9f58d32134e4dd7f306950a69a97ba5a461b7073/CacheNesting.module#L268

**Comment by janKir** [comment]
Thanks! I changed both lines.

**Comment by kixe** [comment]
If you make changes to the module it is recommended to **increment the version number** to see always the last version in the modules directory (updated regularly) of ProcessWire. In the modules info array you maybe want to set your forum name:
`'author' => 'JohnK'`
which makes it easier for ProcessWire forum members to get in touch with you. A link to your personal modules directory will be provided too.

**Comment by janKir** [comment]
Thanks for this info. Updated the meta, as well.
